import { useEffect, useState } from 'react'
type Attempt = {attempt_number:number;status:string;started_at?:string;completed_at?:string;provider_pin_id?:string;error_code?:string;safe_response_metadata?:Record<string,unknown>}
type Publication = { id:string; status:string; revision_id?:string; creative_id?:string; approval_id?:string; pinterest_connection_id?:string; pinterest_board_id?:string; scheduled_for?:string; published_at?:string; pinterest_pin_id?:string; error_code?:string; scheduler_foundation_available?:boolean; live_publishing_enabled?:boolean; publishing_readiness_reason?:string; attempts?:Attempt[] }
export function PublicationsPage() {
  const [rows,setRows]=useState<Publication[]>([])
  const [error,setError]=useState<string|null>(null)
  const load=()=>fetch('/api/publications',{credentials:'include'}).then(async r=>{if(!r.ok) throw new Error(`Request failed (${r.status})`); return r.json()}).then(setRows).catch(e=>setError(e.message))
  useEffect(()=>{load()},[])
  const mutate=async (id:string, action:string, body?:object)=>{setError(null); const r=await fetch(`/api/publications/${id}/${action}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Origin':window.location.origin},body:body?JSON.stringify(body):undefined}); if(!r.ok){setError(`Request failed (${r.status})`);return} await load()}
  return <section><header><div><p className="eyebrow">PUBLICATIONS / SCHEDULER</p><h2>Publication queue</h2><p>Scheduler foundation: {rows[0]?.scheduler_foundation_available?'available':'unavailable'} · Live publishing: {rows[0]?.live_publishing_enabled?'enabled':'disabled'}</p></div></header>{error&&<section className="panel"><strong>{error}</strong></section>}{rows.map(row=><article className="panel" key={row.id}><h3>{row.id}</h3><p>Status: {row.status} · Readiness: {row.publishing_readiness_reason||'—'}</p><p>Revision: {row.revision_id || 'original'} · Creative: {row.creative_id || '—'} · Approval: {row.approval_id || '—'}</p><p>Connection: {row.pinterest_connection_id || '—'} · Board: {row.pinterest_board_id || '—'}</p><p>Scheduled: {row.scheduled_for || '—'} · Published: {row.published_at || '—'} · Pin: {row.pinterest_pin_id || '—'}</p>{row.error_code&&<p>Safe error: {row.error_code}</p>}{(row.status==='APPROVED'||row.status==='SCHEDULED'||row.status==='PUBLISH_FAILED')&&<button onClick={()=>mutate(row.id,'schedule',{scheduled_for:new Date(Date.now()+3600000).toISOString()})}>{row.status==='SCHEDULED'?'Reschedule':'Schedule'}</button>}{row.status==='SCHEDULED'&&<button onClick={()=>mutate(row.id,'cancel')}>Cancel</button>}{row.attempts?.map(a=><p key={a.attempt_number}>Attempt #{a.attempt_number}: {a.status} · {a.provider_pin_id||'—'} · {a.error_code||'—'}</p>)}</article>)}</section>
}
