import { useEffect, useState } from 'react'
import { authorizationPath, authorizationPayload, performOneShotDispatch, publishRequest, readinessKey, readinessPath, type DispatchProvider } from './publicationDispatch'

type Attempt = { attempt_number: number; status: string; started_at?: string | null; completed_at?: string | null; provider_pin_id?: string | null; error_code?: string | null; safe_response_metadata?: Record<string, unknown> }
type AuthorizationState = { status?: string; expires_at?: string | null; dispatch_provider?: 'pinterest_direct' | 'buffer' | null }
type Preview = { title?: string | null; description?: string | null; alt_text?: string | null; destination_url?: string | null; utm_url?: string | null; media_url?: string | null; approval_id?: string | null; revision_id?: string | null; creative_id?: string | null; source_image_id?: string | null; template_key?: string | null; template_version?: string | number | null; board_name?: string | null; external_board_id?: string | null; scheduled_for?: string | null; published_at?: string | null; pinterest_pin_id?: string | null; confirmation_prompt?: string; confirmation_text_version?: string; authorization?: AuthorizationState; quality?: { status?: string; policy_version?: string; checks?: { code: string; passed: boolean; severity?: string; message?: string }[] }; duplicate?: { status?: string }; attempts?: Attempt[]; reconciliation?: { action?: string; actor?: string; previous_status?: string; new_status?: string; provider_pin_id?: string | null; reason?: string | null; created_at?: string }[]; checklist?: { code: string; passed: boolean; status?: string }[] }
type Readiness = { dispatch_provider?: 'pinterest_direct' | 'buffer'; manual_status?: string; manual_ready?: boolean; provider_status?: string; live_provider_write_enabled?: boolean; quality?: { status?: string }; duplicate?: { status?: string }; authorization?: AuthorizationState; blocked_reasons?: string[]; reasons?: string[] }
type Publication = { id: string; status: string; revision_id?: string | null; creative_id?: string | null; approval_id?: string | null; scheduled_for?: string | null; published_at?: string | null; pinterest_pin_id?: string | null; error_code?: string | null; scheduler_foundation_available?: boolean; live_publishing_enabled?: boolean; publishing_readiness_reason?: string | null; title?: string | null; description?: string | null; alt_text?: string | null; destination_url?: string | null; utm_url?: string | null; media_url?: string | null; attempts?: Attempt[] }

const scheduleable = new Set(['APPROVED', 'SCHEDULED', 'PUBLISH_FAILED'])
const cancellable = scheduleable
async function apiError(response: Response) { try { const body = await response.json() as { detail?: unknown }; if (typeof body.detail === 'string') return body.detail } catch { /* fallback */ } return `Request failed (${response.status})` }
function iso(value: string) { const date = new Date(value); return value && !Number.isNaN(date.getTime()) ? date.toISOString() : null }
function authoritativeReasons(gate?: Readiness) {
  if (!gate) return []
  if (gate.blocked_reasons?.length) return gate.blocked_reasons
  if (gate.reasons?.length) return gate.reasons
  const reasons: string[] = []
  if (gate.quality?.status && gate.quality.status !== 'PASS') reasons.push(`QUALITY_${gate.quality.status}`)
  if (gate.duplicate?.status && gate.duplicate.status !== 'SAFE_TO_CONTINUE') reasons.push(`DUPLICATE_${gate.duplicate.status}`)
  if (gate.manual_ready === false && gate.manual_status) reasons.push(gate.manual_status)
  if (gate.dispatch_provider === 'pinterest_direct' && gate.provider_status && gate.provider_status !== 'READY') reasons.push(gate.provider_status)
  if (gate.authorization?.status && gate.authorization.status !== 'ACTIVE') reasons.push(gate.authorization.status)
  return reasons
}

export function PublicationsPage() {
  const [rows, setRows] = useState<Publication[]>([]); const [previews, setPreviews] = useState<Record<string, Preview>>({}); const [readiness, setReadiness] = useState<Record<string, Readiness>>({}); const [providers, setProviders] = useState<Record<string, DispatchProvider>>({}); const [confirmed, setConfirmed] = useState<Record<string, boolean>>({}); const [schedule, setSchedule] = useState<Record<string, string>>({}); const [reasons, setReasons] = useState<Record<string, string>>({}); const [pins, setPins] = useState<Record<string, string>>({}); const [dispatchLocked, setDispatchLocked] = useState<Record<string, boolean>>({}); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const load = async () => { try { const r = await fetch('/api/publications', { credentials: 'include' }); if (!r.ok) throw new Error(await apiError(r)); setRows(await r.json() as Publication[]); setError(null) } catch (e) { setError(e instanceof Error ? e.message : 'Request failed') } }
  useEffect(() => { void load() }, [])
  const refreshPublication = async (id: string, provider: DispatchProvider = providers[id] || 'direct') => { const [p, r] = await Promise.all([fetch(`/api/publications/${id}/preview`, { credentials: 'include' }), fetch(readinessPath(id, provider), { credentials: 'include' })]); if (!p.ok || !r.ok) throw new Error(!p.ok ? await apiError(p) : await apiError(r)); const preview = await p.json() as Preview; const gate = await r.json() as Readiness; setPreviews(v => ({ ...v, [id]: preview })); setReadiness(v => ({ ...v, [readinessKey(id, provider)]: gate })) }
  const refreshAll = async (id?: string, provider?: DispatchProvider) => { await load(); if (id) await refreshPublication(id, provider) }
  const request = async (id: string, path: string, body?: object, provider?: DispatchProvider) => { setBusy(id); setError(null); try { const r = await fetch(path, { method: 'POST', credentials: 'include', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); if (!r.ok) throw new Error(await apiError(r)); await refreshAll(id, provider) } catch (e) { setError(e instanceof Error ? e.message : 'Request failed') } finally { setBusy(null) } }
  const authorize = (row: Publication, preview: Preview) => { const provider = providers[row.id] || 'direct'; if (!confirmed[row.id] || !preview.confirmation_text_version) return; setConfirmed(v => ({ ...v, [row.id]: false })); void request(row.id, authorizationPath(row.id, provider), authorizationPayload(preview.confirmation_text_version), provider) }
  const dispatch = async (row: Publication) => { const provider = providers[row.id] || 'direct'; if (dispatchLocked[row.id] || !window.confirm(`Dispatch this exact publication once via ${provider === 'buffer' ? 'Buffer pilot' : 'Direct Pinterest'}? This request will not be retried automatically.`)) return; const req = publishRequest(row.id, provider); const { url, ...init } = req; setDispatchLocked(v => ({ ...v, [row.id]: true })); setBusy(row.id); setError(null); const result = await performOneShotDispatch(async () => { const response = await fetch(url, init); if (!response.ok) throw new Error(await apiError(response)); return response }, async () => refreshAll(row.id, provider)); setBusy(null); if (result.refreshError) { setError('Dispatch outcome could not be confirmed. Do not retry. Reload authoritative state before any further action.') } else if (result.sendError) { setError(result.sendError instanceof Error ? `${result.sendError.message}. Dispatch remains locked; review the refreshed state.` : 'Dispatch failed. Dispatch remains locked; review the refreshed state.') } }
  const reconcile = (row: Publication, action: 'PROVIDER_PIN_CONFIRMED' | 'CANCELLED_UNKNOWN') => { const value = action === 'PROVIDER_PIN_CONFIRMED' ? pins[row.id]?.trim() : reasons[row.id]?.trim(); if (!value) { setError(action === 'PROVIDER_PIN_CONFIRMED' ? 'Enter a verified provider Pin ID.' : 'Enter a cancellation reason.'); return } if (!window.confirm(action === 'CANCELLED_UNKNOWN' ? 'Confirm cancellation. This outcome will never be retried.' : 'Confirm the provider Pin ID was independently verified.')) return; void request(row.id, `/api/publications/${row.id}/reconcile`, action === 'PROVIDER_PIN_CONFIRMED' ? { action, confirmed: true, provider_pin_id: value } : { action, confirmed: true, reason: value }) }
  return <section className="publications"><header><div><p className="eyebrow">PUBLICATIONS / OPERATOR CONSOLE</p><h2>Publication queue</h2><p>Explicit review, authorization, and one-shot dispatch. Provider writes are never retried from this screen.</p></div><div className="header-status"><span className="gate">Human-controlled dispatch</span><span className="connection-state"><i className="status-dot" /> Scheduler {rows.some(r => r.scheduler_foundation_available) ? 'available' : 'checking'}</span></div></header>
    {error && <section className="operator-alert"><strong>Action stopped</strong><span>{error}</span></section>}
    {rows.length === 0 && <section className="panel empty-state"><strong>No publications are queued.</strong><p>Approved publications will appear here for deliberate operator review.</p></section>}
    <div className="publication-list">{rows.map(row => { const preview = previews[row.id]; const provider = providers[row.id] || 'direct'; const ready = readiness[readinessKey(row.id, provider)]; const expectedAuthProvider = provider === 'buffer' ? 'buffer' : 'pinterest_direct'; const gateMatches = ready?.dispatch_provider === expectedAuthProvider; const auth = ready?.authorization; const authorizationMatches = auth?.dispatch_provider === expectedAuthProvider; const reasonsList = authoritativeReasons(ready); const canAuthorize = Boolean(gateMatches && preview?.confirmation_text_version && ready?.manual_ready && ready?.quality?.status === 'PASS' && ready?.duplicate?.status === 'SAFE_TO_CONTINUE' && ['AUTHORIZATION_REQUIRED', 'AUTHORIZATION_EXPIRED', 'AUTHORIZATION_REVOKED'].includes(auth?.status || 'AUTHORIZATION_REQUIRED')); const unknown = row.status === 'PUBLISH_UNKNOWN'; const busyNow = busy === row.id; return <article className={`panel publication-card ${unknown ? 'unknown-card' : ''}`} key={row.id}>
      <div className="publication-heading"><div><span className="record-label">PUBLICATION RECORD</span><h3>{row.id}</h3></div><span className={`status-chip status-${row.status.toLowerCase()}`}>{row.status}</span></div>
      <div className="operator-grid"><div><small>Readiness</small><strong>{ready?.manual_status || row.publishing_readiness_reason || 'Not loaded'}</strong></div><div><small>Provider writes</small><strong>{provider === 'buffer' ? 'Preflight at dispatch' : ready ? (ready.live_provider_write_enabled ? 'Enabled' : 'Disabled') : (row.live_publishing_enabled ? 'Enabled' : 'Disabled')}</strong></div><div><small>Revision</small><strong>{row.revision_id || 'Original'}</strong></div></div>
      <div className="row-actions"><button onClick={() => { void refreshPublication(row.id).catch(e => setError(e instanceof Error ? e.message : 'Preview request failed')) }} disabled={busyNow}>Load preview + readiness</button>{preview && <span className="loaded-note">Loaded for audit</span>}</div>
      {preview && <section className="audit-panel"><div className="audit-columns"><div><h4>Immutable approved content</h4><p><b>Title</b> {preview.title || row.title || '—'}</p><p><b>Description</b> {preview.description || row.description || '—'}</p><p><b>Alt text</b> {preview.alt_text || row.alt_text || '—'}</p><p><b>Destination</b> {preview.destination_url || row.destination_url || '—'}</p><p><b>UTM</b> {preview.utm_url || row.utm_url || '—'}</p>{preview.media_url && <img className="preview-image" src={preview.media_url} alt={preview.alt_text || 'Approved publication'} />}</div><div><h4>Authoritative gates</h4><p>Quality: <b>{ready?.quality?.status || '—'}</b> · Duplicate: <b>{ready?.duplicate?.status || '—'}</b></p><p>Manual: <b>{ready?.manual_status || '—'}</b> · Provider: <b>{ready?.provider_status || '—'}</b></p>{reasonsList.length > 0 && <div className="blocked-reasons"><strong>Blocked by server</strong>{reasonsList.map(reason => <span key={reason}>{reason}</span>)}</div>}{ready && reasonsList.length === 0 && <p className="clear-note">No authoritative blocked reasons reported.</p>}</div></div>
        <div className="provider-choice"><strong>Dispatch provider</strong><label><input type="radio" name={`provider-${row.id}`} checked={provider === 'direct'} onChange={() => { setProviders(v => ({ ...v, [row.id]: 'direct' })); void refreshPublication(row.id, 'direct').catch(e => setError(e instanceof Error ? e.message : 'Readiness request failed')) }} /> Direct Pinterest</label><label><input type="radio" name={`provider-${row.id}`} checked={provider === 'buffer'} onChange={() => { setProviders(v => ({ ...v, [row.id]: 'buffer' })); void refreshPublication(row.id, 'buffer').catch(e => setError(e instanceof Error ? e.message : 'Readiness request failed')) }} /> Buffer pilot</label></div>
        {canAuthorize && <div className="confirmation-box"><p>{preview.confirmation_prompt || 'Review the exact approved publication before authorizing manual dispatch.'}</p><label><input type="checkbox" checked={Boolean(confirmed[row.id])} onChange={e => setConfirmed(v => ({ ...v, [row.id]: e.target.checked }))} /> I confirm this exact approved publication was reviewed.</label><button disabled={!confirmed[row.id] || busyNow} onClick={() => authorize(row, preview)}>Authorize {provider === 'buffer' ? 'Buffer' : 'Direct Pinterest'} dispatch</button></div>}
        {auth?.status === 'ACTIVE' && <div className="confirmation-box"><p>Authorization active for {auth.dispatch_provider === 'buffer' ? 'Buffer pilot' : 'Direct Pinterest'}{auth.expires_at ? ` until ${auth.expires_at}` : ''}.</p>{!authorizationMatches && <p>Choose the authorized provider to dispatch. The authorization cannot be reused across providers.</p>}</div>}
        {auth?.status === 'ACTIVE' && authorizationMatches && gateMatches && !unknown && <div className="dispatch-zone"><span>{dispatchLocked[row.id] ? 'Dispatch already requested from this screen. Reload authoritative state; do not retry.' : 'Ready to send once. No retry.'}</span><button className="dispatch-button" disabled={busyNow || dispatchLocked[row.id] || row.status === 'PUBLISHING'} onClick={() => void dispatch(row)}>Dispatch via {provider === 'buffer' ? 'Buffer pilot' : 'Direct Pinterest'}</button></div>}
        {unknown && <div className="reconcile-box"><h4>Reconciliation required — non-retryable</h4><p>UNKNOWN means the provider outcome cannot be inferred. Resolve independently; do not dispatch again.</p><input value={pins[row.id] || ''} onChange={e => setPins(v => ({ ...v, [row.id]: e.target.value }))} placeholder="Verified provider Pin ID" /><button disabled={busyNow || !pins[row.id]?.trim()} onClick={() => reconcile(row, 'PROVIDER_PIN_CONFIRMED')}>Confirm provider Pin</button><input value={reasons[row.id] || ''} onChange={e => setReasons(v => ({ ...v, [row.id]: e.target.value }))} placeholder="Cancellation reason" /><button className="danger-button" disabled={busyNow || !reasons[row.id]?.trim()} onClick={() => reconcile(row, 'CANCELLED_UNKNOWN')}>Cancel unknown outcome</button></div>}
        <details><summary>Audit trail and attempts</summary>{preview.attempts?.map(a => <p key={a.attempt_number}>Attempt #{a.attempt_number}: {a.status} · {a.started_at || '—'} → {a.completed_at || '—'} · {a.error_code || '—'}</p>)}{preview.reconciliation?.map((e, i) => <p key={i}>Reconciliation: {e.action || '—'} · {e.previous_status || '—'} → {e.new_status || '—'} · {e.reason || '—'}</p>)}</details>
      </section>}
      {scheduleable.has(row.status) && <div className="schedule-bar"><input type="datetime-local" value={schedule[row.id] || ''} onChange={e => setSchedule(v => ({ ...v, [row.id]: e.target.value }))} /><button disabled={busyNow || !schedule[row.id]} onClick={() => { const value = iso(schedule[row.id]); if (value) void request(row.id, `/api/publications/${row.id}/schedule`, { scheduled_for: value }); else setError('Choose a valid scheduled time.') }}>{row.status === 'APPROVED' ? 'Schedule' : 'Reschedule'}</button>{cancellable.has(row.status) && <button disabled={busyNow} onClick={() => void request(row.id, `/api/publications/${row.id}/cancel`)}>Cancel</button>}</div>}
    </article> })}</div></section>
}